"""add card image path

Revision ID: 002
Revises: 001
Create Date: 2026-09-01 18:07:18.896940
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '002'
down_revision: str | Sequence[str] | None = '001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'image_path')
    # ### end Alembic commands ###
